{% set name = "colcon-core" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5edddfc307f8da4712409552ba4e15eed6c4b0b00545ec24afcb70872f24a683

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]
  entry_points:
    - colcon = colcon_core.command:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - coloredlogs  # [win]
    - distlib
    - EmPy
    - pytest
    - pytest-cov
    - pytest-repeat
    - pytest-rerunfailures
    - pytest-runner
    - setuptools >=30.3.0

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    colcon is a command line tool to improve the workflow of building,
    testing and using multiple software packages.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
